name: build wheels for windows

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        architecture: [x64, x86]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        architecture: ${{ matrix.architecture }}
        python-version: ${{ matrix.python-version }}
    - name: build wheel
      run: |
        git submodule update --init --recursive
        pip install -U wheel
        python setup.py bdist_wheel
      shell: bash
    - name: upload wheel
      uses: actions/upload-artifact@v1
      with:
        name: dist_${{ matrix.os }}_${{ matrix.architecture }}_${{ matrix.python-version }}
        path: dist
